on:
  push:
    branches: main

name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: 🔨 Build Project
        run: |
          npm install
          npm run build

      - name: Upload .next folder
        uses: actions/upload-artifact@v3
        with:
          name: dot_next_folder
          path: .next/

      - name: Creating restart file
        run: |
          mkdir tmp && touch tmp/restart.txt 
          echo $RANDOM > tmp/restart.txt

      - name: download .next folder
        uses: actions/download-artifact@v3
        with:
          name: dot_next_folder
          path: .next
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_NAME }}
          password: ${{ secrets.FTP_PASSWORD }}
